Revert "update dependencies"
This reverts commit b752a6ca28f6878abbeef11e44b62cf70d900f87.

Reason: compile error with Go 1.16 for Windows:

```
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.1.0/windows/syscall.go:84:16: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.1.0/windows/syscall_windows.go:141:29: undefined: unsafe.Slice
```